### ISSUE TITLE
Integration unifigateway not found when trying to verify its sensor platform.

### ISSUE THREAD

**Issue by jjanderson** [custom-components/sensor.unifigateway#8]
Hi,

I am getting the above mentioned error being displayed when I "check Config" in the Configuration validation. This was working but is no longer. Can you test with the latest version of HA and advise?

Thanks

**Comment by jjanderson** [comment]
after further investigation, it would appear that you need an init file as of 0.92...

**Comment by Goudtik** [comment]
I had the same error on 0.93.1 
I created a file in the unifigateway folder named manifest.json. This file contains: 

{
  "domain": "unifi_sensor",
  "name": "Unifi",
  "documentation": "https://github.com/custom-components/sensor.unifigateway",
  "requirements": [],
  "dependencies": [],
  "codeowners": []
}

After that everything works and the error has not show up since... Hope this helps.

**Comment by jjanderson** [comment]
manifest file resolves this issue
